"""Derived views over the authoritative decisions, and the metrics contract.

Everything here is computed from `combined-decisions` and `cluster-decisions` and records the
digest it was derived from. Nothing here is authoritative: if a view ever disagreed with the
decisions it summarises, the view is wrong.

The metrics report distinguishes two kinds of absence, and refuses to conflate either with
zero:

- `unknown` -- the metric applies, but this layer has no evidence for it. Canonical counts
  and DAG closure are unknown because no Canonical Ontology exists yet; false merge rate is
  unknown because there is no independent gold set.
- a measured value -- ingestion counts, candidate counts, quarantine classes, channel
  agreement, reproducibility.

Writing 0 where the answer is unknown would read as "checked, none found", which is a
stronger claim than this layer can support. A test asserts these stay `unknown` so they are
never quietly filled in.
"""

from __future__ import annotations

from collections import Counter
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from memory_assertion_v1.alignment.canonical_bytes import digest
from memory_assertion_v1.alignment.decisions import ClusterDecision, CombinedDecision

NonEmptyString = Annotated[str, Field(min_length=1)]
Sha256Hex = Annotated[str, Field(pattern=r"^[a-f0-9]{64}$")]

UNKNOWN = "unknown"

# Metrics from the specification's section 7 that this layer cannot measure, with the reason.
# Held as data so the report and its test read from one list.
UNMEASURABLE_METRICS: dict[str, str] = {
    "accepted_canonical_concept_count": "no Canonical Ontology is generated by this layer",
    "accepted_canonical_operator_count": "no Canonical Ontology is generated by this layer",
    "canonical_dag_closure": "no Canonical Concept graph exists to close",
    "resolved_lexicalization_coverage": "no Canonical owner exists to carry lexicalizations",
    "duplicate_semantic_identity_rate": "requires Canonical identities and independent review",
    "false_merge_rate": "requires an independent gold set",
}


class _ReportRecord(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class IngestionCounts(_ReportRecord):
    """Measured source ingestion, per source.

    schema.org is counted twice on purpose. The graph declares 1,010 `rdfs:Class` and 1,676
    `rdf:Property` nodes, but 232 of them are foreign vocabulary stubs with no `rdfs:label` --
    `unece:Invoice`, `fibo-fnd-plc-adr:PostalAddress`, `snomed:387713003` -- present only so
    schema.org's own `equivalentClass` assertions have a subject to name. Ingestion skips them
    because a term with no surface form yields no lexicalization candidate.

    Recording both numbers keeps a published figure from looking like a parser defect, and the
    stubs are themselves evidence for this layer's central finding: schema.org's asserted
    equivalences point outside these three corpora.
    """

    wordnet_sense_count: int
    wordnet_distinct_lemma_count: int
    propbank_frame_file_count: int
    propbank_roleset_occurrence_count: int
    propbank_unique_roleset_id_count: int
    propbank_role_count: int
    schema_org_declared_class_count: int
    schema_org_declared_property_count: int
    schema_org_labeled_class_count: int
    schema_org_labeled_property_count: int
    schema_org_enumeration_member_count: int
    schema_org_unlabeled_foreign_stub_count: int


class QuarantineSummary(_ReportRecord):
    """A derived view: counts by reason, and the decision ids behind each.

    Ids rather than copies of the decisions, so the summary cannot drift from the authority it
    points at.
    """

    derived_from_sha256: Sha256Hex
    pair_counts_by_reason: dict[str, int]
    cluster_counts_by_reason: dict[str, int]
    pair_decision_ids_by_reason: dict[str, tuple[str, ...]]
    cluster_ids_by_reason: dict[str, tuple[str, ...]]


class AlignmentMetrics(_ReportRecord):
    """Section 7 metrics, split into measured values and explicit unknowns."""

    derived_from_sha256: Sha256Hex
    source_ingestion: IngestionCounts
    candidate_pair_count: int
    promotable_pair_count: int
    rejected_pair_count: int
    quarantined_pair_count: int
    promotable_cluster_count: int
    quarantined_cluster_count: int
    channel_agreement_rate: str
    gate_failure_counts_by_code: dict[str, int]
    unknown_metrics: dict[str, str]
    reproducibility: Literal["verified", "unknown"]


def _agreement_rate(decisions: tuple[CombinedDecision, ...]) -> str:
    """Fraction of pairs where both channels returned the same verdict.

    Rendered as a string with fixed precision because a float would be a reproducibility
    hazard in a hashed artifact, and `unknown` needs somewhere to live when there are no pairs
    -- 0/0 is not 0%.
    """
    if not decisions:
        return UNKNOWN
    agreed = sum(
        1
        for decision in decisions
        if len({result.verdict for result in decision.channel_results}) == 1
    )
    return f"{agreed}/{len(decisions)}"


def summarize_quarantine(
    decisions: tuple[CombinedDecision, ...], clusters: tuple[ClusterDecision, ...]
) -> QuarantineSummary:
    """Build the quarantine view from the authoritative decisions."""
    authority = digest(
        {
            "pairs": [decision.model_dump(mode="json") for decision in decisions],
            "clusters": [cluster.model_dump(mode="json") for cluster in clusters],
        }
    )
    pair_ids: dict[str, list[str]] = {}
    for decision in decisions:
        if decision.disposition == "quarantined" and decision.quarantine_reason:
            pair_ids.setdefault(decision.quarantine_reason, []).append(decision.decision_id)
    cluster_ids: dict[str, list[str]] = {}
    for cluster in clusters:
        if cluster.disposition == "quarantined" and cluster.quarantine_reason:
            cluster_ids.setdefault(cluster.quarantine_reason, []).append(
                cluster.projected_cluster_id
            )
    return QuarantineSummary(
        derived_from_sha256=authority,
        pair_counts_by_reason={key: len(value) for key, value in sorted(pair_ids.items())},
        cluster_counts_by_reason={
            key: len(value) for key, value in sorted(cluster_ids.items())
        },
        pair_decision_ids_by_reason={
            key: tuple(sorted(value)) for key, value in sorted(pair_ids.items())
        },
        cluster_ids_by_reason={
            key: tuple(sorted(value)) for key, value in sorted(cluster_ids.items())
        },
    )


def build_metrics(
    decisions: tuple[CombinedDecision, ...],
    clusters: tuple[ClusterDecision, ...],
    ingestion: IngestionCounts,
    gate_failure_codes: tuple[str, ...],
    *,
    reproducibility: Literal["verified", "unknown"],
) -> AlignmentMetrics:
    """Assemble the metrics report, carrying the unknowns forward explicitly."""
    authority = digest(
        {
            "pairs": [decision.model_dump(mode="json") for decision in decisions],
            "clusters": [cluster.model_dump(mode="json") for cluster in clusters],
        }
    )
    dispositions = Counter(decision.disposition for decision in decisions)
    cluster_dispositions = Counter(cluster.disposition for cluster in clusters)
    return AlignmentMetrics(
        derived_from_sha256=authority,
        source_ingestion=ingestion,
        candidate_pair_count=len(decisions),
        promotable_pair_count=dispositions["promotable"],
        rejected_pair_count=dispositions["rejected"],
        quarantined_pair_count=dispositions["quarantined"],
        promotable_cluster_count=cluster_dispositions["promotable"],
        quarantined_cluster_count=cluster_dispositions["quarantined"],
        channel_agreement_rate=_agreement_rate(decisions),
        gate_failure_counts_by_code=dict(sorted(Counter(gate_failure_codes).items())),
        unknown_metrics=dict(sorted(UNMEASURABLE_METRICS.items())),
        reproducibility=reproducibility,
    )
