"""Mapper v2: the blind interface over structural candidate generation.

Blindness is unchanged from v1 and is structural: input is an utterance and a speaker, the id is
opaque, and there is no field for a question, a gold label, a split or a dataset name.

What changed is underneath. Candidates come from PropBank rolesets, whole-phrase and single-word
ontology aliases, schema.org types and WordNet senses, and a no-map is produced by the generator
rather than by a filter. The three outcomes are therefore all native:

``mapped``
    one candidate is best supported

``ambiguous``
    two or more candidates are supported comparably, so reporting one would hide the competition

``no_map``
    no admissible evidence, which is the correct answer for most conversational turns
"""

from __future__ import annotations

import hashlib
from collections.abc import Sequence
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, model_validator

from ke_memory_demo.core.json import JsonObject, canonical_json

from .candidate_generation import Candidate, CandidateGenerator, build_ontology_entries
from .l2_derivation import L2Deriver
from .source_indices import SourceIndices, build_source_indices

NonEmptyString = Annotated[str, Field(min_length=1)]

MAPPER_ID = "mapper-v2-structural"
MAPPER_VERSION = "2.0.0"

# Two candidates count as competing when the weaker one reaches this share of the stronger. Not a
# tuned accuracy knob: it expresses when two readings are close enough that choosing silently would
# misreport a genuine ambiguity as a confident answer.
AMBIGUITY_RATIO = 0.85


class MapperV2Error(ValueError):
    """A mapper was given something it must not see, or configured incorrectly."""


class Outcome(StrEnum):
    MAPPED = "mapped"
    AMBIGUOUS = "ambiguous"
    NO_MAP = "no_map"


class _Record(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class ExpressionInput(_Record):
    """An utterance and its speaker. There is nowhere to put anything else."""

    expression_id: NonEmptyString
    speaker: NonEmptyString
    text: NonEmptyString

    @model_validator(mode="after")
    def _reject_disclosing_id(self) -> ExpressionInput:
        lowered = self.expression_id.lower()
        for marker in ("beam", "locomo", "longmemeval", "slice", "gold", "valid"):
            if marker in lowered:
                raise MapperV2Error(
                    f"expression_id {self.expression_id!r} discloses dataset identity; ids must be "
                    "opaque so a mapper cannot special-case a corpus"
                )
        return self


class MappingResult(_Record):
    """The raw result. Candidates and their evidence are preserved as generated."""

    expression_id: NonEmptyString
    outcome: Outcome
    candidates: tuple[JsonObject, ...]
    top_ontology_id: str = ""
    top_sense: str = ""
    competing_ontology_ids: tuple[str, ...] = ()
    margin: float | None = None

    @model_validator(mode="after")
    def _validate(self) -> MappingResult:
        if self.outcome is Outcome.NO_MAP:
            if self.candidates or self.top_ontology_id:
                raise MapperV2Error(
                    "a no_map must carry no candidate: it is generated by finding no admissible "
                    "evidence, not by filtering a candidate out afterwards"
                )
        elif not self.candidates:
            raise MapperV2Error("a mapped or ambiguous result requires candidates")
        if self.outcome is Outcome.AMBIGUOUS and len(self.competing_ontology_ids) < 2:
            raise MapperV2Error("an ambiguous result must name at least two competing items")
        return self


class MapperV2:
    """The mapper. Reads an utterance and the frozen ontology, and nothing else."""

    def __init__(
        self,
        ontology_dir: Path,
        *,
        indices: SourceIndices | None = None,
        top_k: int = 5,
        ambiguity_ratio: float = AMBIGUITY_RATIO,
    ) -> None:
        import json

        l1 = json.loads((ontology_dir / "o_l1.json").read_text(encoding="utf-8"))
        l2 = json.loads((ontology_dir / "o_l2.json").read_text(encoding="utf-8"))
        self._o_l1_sha256 = str(l1["freeze"]["sha256"])
        self._o_l2_sha256 = str(l2["freeze"]["sha256"])
        self._indices = indices if indices is not None else build_source_indices()
        self._ambiguity_ratio = ambiguity_ratio
        self._generators = {
            "l1": CandidateGenerator(
                build_ontology_entries(l1["items"]), self._indices, top_k=top_k
            ),
        }
        # L2 is derived from L1 through the frozen map rather than indexed by its own aliases. The
        # contract review found direct indexing returned no_map for clear abstractions, because a
        # habit utterance contains no word from the habit item's alias list.
        self._l2 = L2Deriver(ontology_dir)

    @property
    def identity(self) -> JsonObject:
        return {
            "mapper_id": MAPPER_ID,
            "mapper_version": MAPPER_VERSION,
            "ambiguity_ratio": self._ambiguity_ratio,
            "o_l1_sha256": self._o_l1_sha256,
            "o_l2_sha256": self._o_l2_sha256,
            "wordnet_sha256": self._indices.wordnet.source_sha256,
            "propbank_sha256": self._indices.propbank.source_sha256,
            "schemaorg_sha256": self._indices.schemaorg.source_sha256,
        }

    def freeze_hash(self) -> str:
        """The mapper's digest, so a run can prove which mapper produced it."""
        return hashlib.sha256(canonical_json(self.identity)).hexdigest()

    def map_expression(self, request: ExpressionInput, layer: str = "l1") -> MappingResult:
        """Map one utterance at one layer, preserving the generated ranking.

        The two layers take different paths on purpose: L1 is recognition from lexical and structural
        evidence, L2 is derivation over attested L1 items. A single figure spanning both would hide
        that difference, so the validation reports them separately.
        """
        if layer not in {"l1", "l2"}:
            raise MapperV2Error(f"unknown layer {layer!r}")

        l1_candidates = self._generators["l1"].generate(request.text)
        candidates = (
            l1_candidates
            if layer == "l1"
            else self._l2.derived_candidates(l1_candidates)
        )
        if not candidates:
            # Native: the generator found no admissible evidence.
            return MappingResult(
                expression_id=request.expression_id,
                outcome=Outcome.NO_MAP,
                candidates=(),
            )

        best = candidates[0]
        competing = self._competing(candidates)
        if len(competing) >= 2:
            return MappingResult(
                expression_id=request.expression_id,
                outcome=Outcome.AMBIGUOUS,
                candidates=tuple(c.as_json() for c in candidates),
                top_ontology_id=best.ontology_id,
                top_sense=best.sense,
                competing_ontology_ids=tuple(c.ontology_id for c in competing),
                margin=(
                    round(best.score - candidates[1].score, 6)
                    if len(candidates) > 1
                    else None
                ),
            )

        return MappingResult(
            expression_id=request.expression_id,
            outcome=Outcome.MAPPED,
            candidates=tuple(c.as_json() for c in candidates),
            top_ontology_id=best.ontology_id,
            top_sense=best.sense,
            margin=(
                round(best.score - candidates[1].score, 6) if len(candidates) > 1 else None
            ),
        )

    def _competing(self, candidates: Sequence[Candidate]) -> tuple[Candidate, ...]:
        """Candidates supported comparably to the best one.

        Structural standing is part of the comparison: a candidate resting on vocabulary alone does
        not compete with one backed by argument structure, however close their scores.
        """
        best = candidates[0]
        threshold = best.score * self._ambiguity_ratio
        return tuple(
            candidate
            for candidate in candidates
            if candidate.score >= threshold
            and candidate.has_structural_evidence == best.has_structural_evidence
        )

    def provenance(self) -> dict[str, Any]:
        return {
            "identity": self.identity,
            "freeze_hash": self.freeze_hash(),
            "generation": self._generators["l1"].provenance(),
            "l2_derivation": self._l2.provenance(),
            "blindness": {
                "inputs": ["expression_id (opaque)", "speaker", "text"],
                "absent_by_construction": [
                    "question",
                    "gold label",
                    "split",
                    "dataset name",
                    "sample id",
                ],
                "enforced_by": (
                    "ExpressionInput declares three fields and forbids extras; an id disclosing a "
                    "corpus is rejected"
                ),
            },
            "no_correction_gate": (
                "a no_map is produced by generation finding no admissible evidence. There is no "
                "post-hoc filter, because a filter measures the filter."
            ),
        }
